# For early development
coverage:
  range: 40..90
  round: down
  precision: 1
  status:
    project:
      default:
        target: 40%
        threshold: 2%
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: true
